

services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://backend:5000"
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always  # Ensures automatic restart if the container crashes

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - PORT=5000
      - JWT_SECRET=mySuperSecretKey12345!
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase

volumes:
  mongodb_data:  # Persistent storage for MongoDB
    driver: local

networks:
  default:
    driver: bridge
